name: ðŸš€ Deploy via SFTP with SSH Key

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete --exclude='.git/' --exclude='.github/' --exclude='.idea/' --exclude='.vscode/' --exclude='README.md' --exclude='.cpanel.yml'"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SFTP_HOST }}
          REMOTE_USER: "khehlacl"
          REMOTE_PORT: "22000"
          TARGET: "/home/khehlacl/public_html/"
