name: ðŸš€ Deploy via SFTP (SSH Key)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to cPanel using SFTP with SSH key
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: 169.239.218.70
          port: 22000
          username: khehlacl
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: "./"
          remote_path: "/home/khehlacl/public_html/"
          sftp_only: true
          sftpArgs: "-o StrictHostKeyChecking=no"
          delete_remote_files: false
