name: ðŸš€ Deploy via SFTP (SSH Key)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to cPanel using SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: "khehlacl"
          port: 22000
          protocol: "sftp"
          private-key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local-dir: "./"
          server-dir: "/home/khehlacl/public_html/"
          exclude: |
            **/.git**
            **/.github/**
            **/.idea/**
            **/.vscode/**
            **/.cpanel.yml
            **/README.md
            **/*.yml
            **/*.yaml
            .gitignore
